<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mercato.AspNetCore.OData.DataTableExtension.Demo</RootNamespace>
	  <Platforms>x64</Platforms>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
	  <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mercato.AspNet.OData.DataTable\Mercato.AspNet.OData.DataTable.csproj" />
  </ItemGroup>

</Project>
